
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM openjdk:17
EXPOSE  8090
ADD target/api.jar api.jar
ENTRYPOINT ["java","-jar","/api.jar"]

